# Generated by Django 4.2.8 on 2024-04-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_return_alter_customer_id_alter_feedback_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/CustomerProfilePic/logo.jpg', null=True, upload_to='profile_pic/CustomerProfilePic/'),
        ),
    ]
