# Generated by Django 4.2.8 on 2024-04-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_product_category_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/user.png', null=True, upload_to='profile_pic/CustomerProfilePic/'),
        ),
    ]
