# Generated by Django 4.2.8 on 2024-05-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0016_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
